# Generated by Django 5.1.4 on 2024-12-05 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Модель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'модель',
                'verbose_name_plural': 'модели',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('color_name', models.CharField(max_length=30, verbose_name='Цвет')),
                ('color_code', models.CharField(max_length=10, verbose_name='Код цвета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Слаг продукта')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='digital.category', verbose_name='Категория')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='digital.model', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото продукта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='digital.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фото',
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Характеристика')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_key', to='digital.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'характеристика',
                'verbose_name_plural': 'характеристики',
            },
        ),
        migrations.CreateModel(
            name='SpecValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='Значение характеристики')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='digital.product', verbose_name='Продукт')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_value', to='digital.spec', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'значение',
                'verbose_name_plural': 'значений',
            },
        ),
    ]
