# Generated by Django 5.1.4 on 2024-12-11 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0003_model_product_productimage_spec_specvalue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specvalue',
            options={'verbose_name': 'значение характеристики', 'verbose_name_plural': 'значение характеристик'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='digital.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='digital.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='digital.model', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='digital.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='spec',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_keys', to='digital.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='specvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='digital.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='specvalue',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_values', to='digital.spec', verbose_name='Характеристика'),
        ),
    ]
